use_frameworks!

platform :ios, '10.0'

target 'BGTableViewComponent_Example' do
  pod 'BGTableViewComponent', :path => '../'

  pod 'Masonry'
  pod 'SDCycleScrollView'
  
  target 'BGTableViewComponent_Tests' do
    inherit! :search_paths

    
  end
end
